name = "lyricgenius-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[vars]
# OPENAI_API_KEY will be configured via `wrangler secret put OPENAI_API_KEY`

[dev]
ip = "127.0.0.1"
port = 8787

